name: dust
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.7.3
  - amply=0.1.4
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attmap=0.12.11
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - bleach=3.3.0
  - blosc=1.21.0
  - bokeh=2.2.3
  - boost-cpp=1.74.0
  - boto3=1.17.6
  - botocore=1.20.6
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.1
  - cairo=1.16.0
  - cartopy=0.18.0
  - cdo=1.9.9
  - cdsapi=0.5.1
  - certifi=2021.5.30
  - cffi=1.14.4
  - cfgrib=0.9.8.5
  - cfitsio=3.470
  - cftime=1.4.1
  - chardet=3.0.4
  - charls=2.2.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - coincbc=2.10.5
  - configargparse=1.2.3
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.2.0
  - dask-core=2021.2.0
  - datrie=0.8.2
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2021.2.0
  - docutils=0.16
  - dropbox=10.9.0
  - eccodes=2.20.0
  - ecmwf-api-client=1.6.1
  - entrypoints=0.3
  - eofs=1.4.0
  - esmf=8.0.1
  - expat=2.2.10
  - fftw=3.3.9
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.5
  - fribidi=1.0.10
  - fsspec=0.8.5
  - ftputil=4.0.0
  - gdal=3.2.1
  - gdk-pixbuf=2.42.2
  - genshi=0.7.5
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - ghostscript=9.53.3
  - giflib=5.2.1
  - git=2.30.1
  - gitdb=4.0.5
  - gitpython=3.1.13
  - glib=2.66.7
  - glib-tools=2.66.7
  - google-api-core=1.25.1
  - google-api-python-client=1.12.8
  - google-auth=1.24.0
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.35.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - grpcio=1.35.0
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.3
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=2.7.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - httplib2=0.19.0
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.1.11
  - imageio=2.9.0
  - imagemagick=7.0.10_62
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - iniconfig=1.1.1
  - ipykernel=5.4.3
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.11
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.2.1
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.14.0
  - librsvg=2.50.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libzopfli=1.0.3
  - llvmlite=0.35.0
  - locket=0.2.0
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - more-itertools=8.7.0
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nco=4.9.7
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.5.1
  - networkx=2.5
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.61
  - numba=0.52.0
  - numpy=1.20.1
  - oauth2client=4.1.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - ossuuid=1.6.2
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - pango=1.42.4
  - paramiko=2.7.2
  - parso=0.8.1
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.44
  - peppy=0.31.0
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - plotly=4.14.3
  - pluggy=0.13.1
  - pooch=1.3.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - prettytable=2.0.0
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - prompt_toolkit=3.0.16
  - protobuf=3.14.0
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.3.1
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.4
  - pygraphviz=1.7
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysftp=0.2.9
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-eccodes=2021.01.0
  - python-irodsclient=0.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qt=5.12.9
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.25.1
  - retrying=1.3.3
  - rsa=4.7
  - s3transfer=0.3.4
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - six=1.15.0
  - slacker=0.14.0
  - smmap=3.0.5
  - snakemake=5.32.1
  - snakemake-minimal=5.32.1
  - snappy=1.1.8
  - sortedcontainers=2.3.0
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - tblib=1.6.0
  - tempest-remap=2.0.5
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.2.0
  - tifffile=2021.2.1
  - tiledb=2.2.3
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - toposort=1.6
  - tornado=6.1
  - tqdm=4.56.2
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2021a
  - ubiquerg=0.6.1
  - udunits2=2.2.27.27
  - uritemplate=3.0.1
  - urllib3=1.26.3
  - veracitools=0.1.3
  - vim=8.2.2501
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xarray=0.16.2
  - xerces-c=3.2.3
  - xlrd=2.0.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
      - "--editable=git+https://github.com/MasterOnDust/Thesis_toolbox#egg=Thesis_toolbox"
      - "--editable=git+https://github.com/MasterOnDust/DUST#egg=DUST"
      - "--editable=git+https://github.com/MasterOnDust/flexpart_cluster#egg=fpcluster"
      
