name: /nird/scratch/ovewh/analysis_workflow
channels:
  - defaults
dependencies:
  - dask[version='>=2021.3.0,<2022.12.0']
  - eccodes[version='>=2.20.0']
  - ecmwf-api-client[version='>=1.6.1']
  - eofs[version='>=1.4.0']
  - esmf[version='>=8.0.1']
  - graphviz[version='>=2.46.1,<7.1.0']
  - notebook[version='>=7.0.0']
  - matplotlib[version='>=3.3.4,<3.7.0']
  - netcdf4
  - pip
  - python-eccodes
  - pygraphviz[version='>=1.7']
  - python[version='>=3.9,<3.12.0']
  - scipy
  - seaborn[version='>=0.11.1']
  - snakemake[version='>=7.0.5,<7.20.0']
  - statsmodels
  - tqdm
  - cartopy[version='>=0.20.0,<0.22.0']
  - zarr[version='>=2.9.0,<2.13.0']
  - xarray[version='>=0.20.0,<2022.12.0']
  - zlib
  - pip:
      - "--editable=git+https://github.com/MasterOnDust/Thesis_toolbox.git@v0.0.1#egg=Thesis_toolbox"
      - "--editable=git+https://github.com/MasterOnDust/DUST.git@0.1.2#egg=dust"
      - "--editable=git+https://github.com/MasterOnDust/flexpart_cluster.git@1.0.1#egg=fpcluster"
