# This file configures the workflow on a global scale.
# Setting the global path variables etss

# Setting different global paths where the result should be stored
# Maybe this should be removed and I'll just hard code the paths?
old_base : "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow"
download_path: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/downloads/downloads/monthly"
figs_path: "results/figs"
intermediate_files: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/downloads/intermediate_results"
nao_output_path: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/nao"
EAWMI_path: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/eawmi"
ao_output_path: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/ao"
APVI_index_outpath: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/apv"
Precipitation: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/precip"
orography_file: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/downloads/downloads/ERA5_orography.nc"


flexpart_path: "/projects/NS2806K/ovewh/tracing_the_winds/flexpart/production_run"
flexdust_path: "../../data/FLEXDUST_emission_flux/FLEXDUST1999_2019"
source_contrib_path: "../../data/flexpart/production_run/improved_kok_flexdust_1999_2019_fixed_scaling"
flexdust_results: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/model_results/flexdust"
intermediate_results_models: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/model_results/intermediate_results"
source_contrib_results: "../../data/Master_thesis_UiO_workflow/Master_thesis_UiO_workflow/results/model_results/source_contrib"
MERRA2_path : "../../data/MERRA2"
# Variables name used to constrain the wildcards

variables:
  - 2m_temperature
  - mean_sea_level_pressure
  - snow_depth
  - temperature
  - Geopotential
  - u_component_of_wind
  - total_precipitation
  - v_component_of_wind
  - snow_cover
  - sea_ice_cover
  - snow_albedo
  - soil_temperature_level_1
  - soil_temperature_level_2
  - volumetric_soil_water_layer_1
  - volumetric_soil_water_layer_2

# Set first and last year to download.
sdate: 1979
edate: 2019

# Set first and last year of FLEXPART/FLEXDUST model output

m_sdate: 1999
m_edate: 2019

# Composite climatological period

clim_date0: 1989
clim_date1: 2019

# Domain for processing FLEXPART/FLEXDUST model output on
domain:
    lon0: 50
    lon1: 128
    lat0: 25
    lat1: 65

# Recepotor Location used in the procject.

receptors:
    SACOL:
        lon: 104.1370
        lat: 35.96400
    BAODE:
        lon: 111.1700
        lat: 39.00300
    LANTIAN:
        lon: 109.2560
        lat: 34.18000
    LINGTAI:
        lon: 107.7890
        lat: 35.71000 
    SHAPOTOU:
        lon: 105.0475
        lat: 34.18000
    YINCHUAN:
        lon: 106.1010
        lat: 38.50000
    LUOCHUAN:
        lat: 109.4240
        lon: 35.71000

source_regions:
        taklamakan:
            lon0: 75
            lon1: 90
            lat0: 36
            lat1: 42
        north_west:
            lon0: 100
            lon1: 110
            lat0: 37
            lat1: 42
        mongolia:
            lon0: 95
            lon1: 110
            lat0: 43
            lat1: 50
        jungger_basin:
            lon0: 80
            lon1: 90
            lat0: 43
            lat1: 47
        quaidam_basin:
            lon0: 90
            lon1: 100
            lat0: 35
            lat1: 40
        central_asia:
            lon0: 56
            lon1: 73
            lat0: 26
            lat1: 47

# Number of latitude bins used in temperature gradient calculation
n_bins_temperature_gradient: 17


# Plotting config:

add_fig_title: True