
#####################################################################################
# Snakefile for downloading and processing monthly ERA5 data                        #
#                                                                                   #
# Created by Ove Haugvaldstad                                                       #
#                                                                                   #
#####################################################################################

# Load config file

configfile: "config/config.yaml"

#----------------------------------CONSTANTS----------------------------------------#

g0=9.80665 #m/s


import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import xarray as xr


from IPython import embed


wildcard_constraints:
    season='DJF|MAM|JJA|SON',
    fig_file_extention='png|pdf'

include: "rules/download.smk"
include: "rules/calc_nao.smk"
include: "rules/utils.smk"
include: "rules/plotting.smk"
include: "rules/calculate_means.smk"
include: "rules/climatology_calculation.smk"
p_level_vars = config['variables_pressure_levels']
SDATE=config['sdate']
EDATE=config['edate']
SEASONS=['DJF','MAM','JJA','SON']
rule all:
    input:
        # expand(config['download_path']+"/era5.{plevel}hPa.{varName}.monthly.{sdate}-{edate}.nc", 
        #                 plevel=p_level_vars['Geopotential'], varName=['temperature', 'Geopotential'],sdate=SDATE, edate=EDATE),
        # expand(config['download_path']+"/era5.single_level.{varName}.monthly.{sdate}-{edate}.nc", 
        #                 varName=config['variables_single_level'], sdate=SDATE, edate=EDATE),
        # expand(config['intermediate_files']+"era5.single_level.{varName}.annual.{sdate}-{edate}.nc", 
        #                 varName=VARNME_SURFACE, sdate=SDATE, edate=EDATE),
        # expand(config['intermediate_files']+"era5.single_level.{varName}.{season}_avg.{sdate}-{edate}.nc", 
        #                 varName=VARNME_SURFACE, sdate=SDATE, edate=EDATE, season=SEASONS),
        # expand(config['intermediate_files']+"era5.{plevel}hPa.{varName}.{season}_avg.{sdate}-{edate}.nc", 
        #                 plevel=PLEVELS, varName=VARNAME_PRESSURE_LEVEL, sdate=SDATE, edate=EDATE, season=SEASONS),
        # expand(config['intermediate_files']+"era5.{plevel}hPa.GeopotHeight.{season}_avg.{sdate}-{edate}.nc", 
        #                 plevel=p_level_vars['Geopotential'], sdate=SDATE, edate=EDATE, season=SEASONS),
        # expand(config['download_path']+"era5.300hPa.u_component_of_wind.monthly.{sdate}-{edate}.nc",
        #                 sdate=SDATE, edate=EDATE),
        # expand(config['figs_path']+"era5.{plevel}hPa.temp_geopot.DJF_JJA_comp_avg.{sdate}-{edate}.png",
        #                 sdate=SDATE, edate=EDATE,plevel=p_level_vars['Geopotential']),
        expand(config['figs_path']+"/era5.single_level.temp2m_mslp.DJF_JJA_comp_avg.{sdate}-{edate}.png",
                        sdate=SDATE, edate=EDATE),

        config['intermediate_files']+"/era5.single_level.mean_sea_level_pressure.monthly_anomaly.1979-2019.nc",
        config['intermediate_files']+"/era5.single_level.mean_sea_level_pressure.DJF_anomaly.1979-2019.nc",
       
        # config['intermediate_files']+"era5.single_level.mean_sea_level_pressure.DJF.1979-2019.nc",
        config['intermediate_files']+"/era5.single_level.NAO.station.DJF.1979-2019.nc"
        # FIGS+"era5.single_level.mslp.DJF_orographic_avg.1979-2019.png"
        # config['intermediate_files']+"/era5.single_level.NAO.monthly.1979-2019.nc"



        

