# This file configures the workflow on a global scale.
# Setting the global path variables etss

# Setting different global paths where the result should be stored
download_path: "/opt/uio/flexpart/ERA5/monthly"
figs_path: "results/figs"
intermediate_files: "/opt/uio/flexpart/ERA5/intermediate_results"
nao_output_path: "results/nao"
EAWMI_path: "results/eawmi"
ao_output_path: "results/ao"

# Variables name used to constrain the wildcards

variables:
  - 2m_temperature
  - mean_sea_level_pressure
  - snow_depth
  - temperature
  - Geopotential
  - u_component_of_wind

# Set first and last year to download.
sdate: 1979
edate: 2019